### ISSUE TITLE
Links to Supplementary Material are broken on Publications page

### ISSUE THREAD

**Issue by alundgard** [mitvis/website#12]
The links to `Supplementary Material` on the [Our Publications page](http://vis.csail.mit.edu/pubs/) are broken. This is because they are missing the relative url to their corresponding pub. The relative url cannot be added directly via the templating language (e.g., adding `{{url}}` in `pubs/index.md` because this breaks other Materials links, which are often absolute urls. Adding the relative url to the pub's `materials` `url` (e.g., in `rich-screen-reader-vis-experiences.md`) doesn't work either, since this breaks the link when navigating from the [corresponding pub page](http://vis.csail.mit.edu/pubs/rich-screen-reader-vis-experiences/), where the relative url is already present. Possible solution: add logic for handling relative versus absolute urls in `pubs/index.md`

**Comment by arvind** [comment]
Fixed with [e64246b](https://github.com/mitvis/website/commit/e64246bdc2b32415d79ba3b6a26c97674e23a90c). Thanks!
